# Generated by Django 4.2.5 on 2023-09-17 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('idfailure', models.AutoField(primary_key=True, serialize=False)),
                ('failuredate', models.DateField()),
                ('failurecause', models.TextField()),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='equipement.equipement')),
            ],
        ),
    ]
