# Generated by Django 4.2.5 on 2023-09-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipementmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementmodel',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='equipement_images/'),
        ),
    ]
