# Generated by Django 4.2.5 on 2023-09-14 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipementmodel', '0003_equipementmodel_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipementmodel',
            name='comments',
        ),
        migrations.AddField(
            model_name='equipementmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
