# Generated by Django 4.2.5 on 2023-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentmodel', '0006_rename_model_associated_comment_equipment_model'),
        ('equipementmodel', '0005_equipementmodel_failure_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementmodel',
            name='comments',
            field=models.ManyToManyField(related_name='equipement_models', to='commentmodel.comment'),
        ),
    ]
