# Generated by Django 4.2.5 on 2023-09-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipementmodel', '0006_equipementmodel_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipementmodel',
            name='comments',
        ),
    ]
