# Generated by Django 4.2.5 on 2023-09-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('idbill', models.AutoField(primary_key=True, serialize=False)),
                ('billfile', models.FileField(upload_to='bills/')),
            ],
        ),
    ]
