# Generated by Django 4.2.5 on 2023-09-17 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipementmodel', '0004_remove_equipementmodel_comments_equipementmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('idequipement', models.AutoField(primary_key=True, serialize=False)),
                ('serialnumber', models.CharField(max_length=255)),
                ('dateinstallation', models.DateField(blank=True, null=True)),
                ('datelastmaintenance', models.DateField(blank=True, null=True)),
                ('currenthealth', models.CharField(blank=True, choices=[('warning', 'Warning'), ('good', 'Good'), ('critical', 'Critical')], max_length=20, null=True)),
                ('failurestate', models.CharField(blank=True, choices=[('red', 'Red'), ('orange', 'Orange'), ('green', 'Green')], max_length=20, null=True)),
                ('failurerisk', models.IntegerField(blank=True, null=True)),
                ('countdowndate', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='equipement_images/')),
                ('equipementmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_model', to='equipementmodel.equipementmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Equipements',
            },
        ),
    ]
