# Generated by Django 4.2.5 on 2023-09-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_alter_bill_equipement'),
        ('failure', '0001_initial'),
        ('equipement', '0002_equipement_shared_with_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='bills',
            field=models.ManyToManyField(blank=True, related_name='equipments_bills', to='bill.bill'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='failure_history',
            field=models.ManyToManyField(blank=True, related_name='equipments_failure', to='failure.failure'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='garantie',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='serialnumber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
