# Generated by Django 4.2.5 on 2023-09-25 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipement', '0003_equipement_bills_equipement_failure_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='bills',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='failure_history',
        ),
        migrations.AlterField(
            model_name='equipement',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, related_name='equipements_shared_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
