# Generated by Django 4.2.5 on 2023-09-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0004_remove_equipement_bills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='countdowndate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
