# Generated by Django 4.2.5 on 2023-09-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentmodel', '0002_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
