# Generated by Django 4.2.5 on 2023-09-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentmodel', '0003_remove_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='model_associated',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
