# Generated by Django 4.2.5 on 2023-09-14 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipementmodel', '0004_remove_equipementmodel_comments_equipementmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentmodel', '0004_remove_comment_model_associated_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='model_associated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_on_equipement', to='equipementmodel.equipementmodel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
