# Generated by Django 4.2.5 on 2023-09-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentmodel', '0005_comment_model_associated_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='model_associated',
            new_name='equipment_model',
        ),
    ]
